variable "projectID" {}
variable "region1" {}
variable "zone1" {}
variable "automation_key" {
  description = "This should be a public ssh key used to connect to linux servers. This is used primarily for an automation user with tools like ansible"
}
variable "client_admin_key" {
  description = "Public SSH key that will be added to project wide metadata. Will generally be the admin user to manage all servers"
}

##+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+
##This full block must be repeated for every different instance type
variable "servers1" {
  description = "Name of the servers, will be followed by a hash generated by the MIG"
}
variable "servers1_machine_type" {}
variable "server1_bootdisk_size" {}
variable "server1_datadisk_size" {}
###Both image family and image project can be from the public images, however, this should match the family and project of your custom image
## See available options for public images @ https://cloud.google.com/compute/docs/images#unshielded-images
variable "servers1_image_family" {}
variable "servers1_image_project" {}

variable "servers1_env" {
  description = "prod, dev, staging, QA, etc."
  default     = "demo"
}
variable "servers1_role" {
  description = "Adds a label to the instance to mark the role of the server (frontend, backend, app, db, etc)"
  default     = "demo"
}
variable "server1_replicas" {
  description = "Set the number of instances that the MIG will maintain"
  type        = "number"
  default     = 1
}

##+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+
##DB settings
variable "db_version" {
  description = "The MySQL, PostgreSQL or SQL server version to use. See https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#database_version for supported versions"
}
variable "db_root_password" {
  description = "only used for MS SQL databases, ignored by MySQL and PostgreSQL"
  default     = "notMSSQL"
}
variable "db_tier" {
  default     = "db-f1-micro"
  description = "macine type used for the db"
}
variable "db_availability" {
  default     = "REGIONAL"
  description = "Availability of the Cloud SQL instances, can be REGIONAL or ZONAL. Defaults to regional"
}

##+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+
##VPC network settings
variable "ipCIDR" {
  type        = "list"
  default     = ["10.0.0.0/24", "10.0.1.0/24", "10.0.2.0/24"]
  description = "IP ranges to assign to subnets. Each subnet will use one from this list. Must contain at least as many ranges as there are subnets"
}

variable "onpremCIDR" {
  default = "192.168.0.0/16"
}
variable "onprem_VPN_IP" {
  description = "public IP of the CVPN gateway on prem. Default value is only present in case no VPN is being used"
  default     = "35.35.35.35"
}
variable "vpn-secret" {
  default     = "novpninuse"
  description = "password used for IPsec tunnel. Default should only be used if you are not using a VPN"
}

variable "podCIDR" {
  type        = "list"
  default     = ["172.16.128.0/20"]
  description = "secondary ip range used for pods in GKE clusters"
}

variable "serviceCIDR" {
  type        = "list"
  default     = ["172.16.0.0/23", "172.16.2.0/23", "172.16.4.0/23", "172.16.6.0/23"]
  description = "Secondary IP range used for services in GKE clusters. One per cluster"
}

variable "specialIPs" {
  type        = "list"
  description = "List of IPs to allow through general firewalls"
  default     = ["0.0.0.0/0"]
}

variable "bastionSourceIP" {
  type        = "list"
  description = "IPs to allow connecting to the bastion"
  default     = ["0.0.0.0/0"]
}
